"""FastAPI app — /predict, /healthz, /readyz endpoints."""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import Annotated

import pandas as pd
from fastapi import Depends, FastAPI, HTTPException, Response
from fastapi.responses import HTMLResponse

from credit_risk.drift.capture import PredictionRow, capture_row, to_dataframe
from credit_risk.drift.store import read_report_html, write_predictions_parquet
from credit_risk.serving.model_loader import ModelBundle, load_staging_model
from credit_risk.serving.schemas import (
    HealthResponse,
    PredictionRequest,
    PredictionResponse,
)

logger = logging.getLogger("credit_risk.serving")

# Module-level slot the lifespan handler fills in. Tests override via
# app.dependency_overrides on `get_bundle` so they never touch MLflow.
_bundle: ModelBundle | None = None

# Prediction-capture buffer — batched flush to MinIO Parquet every N rows.
# In-memory by design: low overhead per request, no extra infra.
# At ~30 RPS and 50-row batches, flushes ~2x per minute.
_PREDICTION_BUFFER: list[PredictionRow] = []
_BUFFER_FLUSH_AT = 50


def _maybe_flush_buffer() -> None:
    """If the buffer is full, write it to today's Parquet partition + reset."""
    global _PREDICTION_BUFFER
    if len(_PREDICTION_BUFFER) < _BUFFER_FLUSH_AT:
        return
    try:
        df = to_dataframe(_PREDICTION_BUFFER)
        write_predictions_parquet(df)
        logger.info("Flushed %d predictions to MinIO", len(df))
    except Exception:
        logger.exception("Failed to flush prediction buffer")
    _PREDICTION_BUFFER = []


def get_bundle() -> ModelBundle | None:
    """Single source of truth for 'is a bundle available right now?'

    Returns the loaded bundle, or None if startup hasn't loaded one yet.
    Endpoints decide for themselves how to handle None: /healthz reports it,
    /readyz returns 503, /predict raises 503.

    Tests override this via ``app.dependency_overrides[get_bundle]``.
    """
    return _bundle


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _bundle
    try:
        _bundle = load_staging_model()
        logger.info(
            "Loaded model v%s with %d features", _bundle.version, len(_bundle.feature_names)
        )
    except Exception as exc:
        logger.exception("Failed to load model on startup: %s", exc)
        _bundle = None
    yield
    _bundle = None


app = FastAPI(
    title="Credit Risk Prediction API",
    version="0.2.0",
    description="Predicts default probability from already-encoded German Credit features.",
    lifespan=lifespan,
)


@app.get("/healthz", response_model=HealthResponse)
def healthz(
    bundle: Annotated[ModelBundle | None, Depends(get_bundle)],
) -> HealthResponse:
    loaded = bundle is not None
    return HealthResponse(status="ok" if loaded else "degraded", model_loaded=loaded)


@app.get("/readyz")
def readyz(
    response: Response,
    bundle: Annotated[ModelBundle | None, Depends(get_bundle)],
) -> dict:
    if bundle is None:
        response.status_code = 503
        return {"ready": False}
    return {"ready": True}


@app.get("/drift", response_class=HTMLResponse)
def drift_report() -> HTMLResponse:
    """Serve the latest pre-computed drift report HTML from MinIO.

    The report is generated by `scripts/drift_check.py` (Day 4) and uploaded
    to `s3://reports/latest.html`. This endpoint just streams the bytes back
    to the browser; no on-demand computation (would block the request).
    """
    try:
        html = read_report_html("latest.html")
        return HTMLResponse(content=html)
    except Exception:
        return HTMLResponse(
            content=(
                "<html><body style='font-family:sans-serif;padding:2rem;'>"
                "<h2>No drift report available yet</h2>"
                "<p>Run <code>make p3-check</code> to generate one. "
                "It compares last 7 days of production traffic against the "
                "training reference and uploads the report to MinIO.</p>"
                "</body></html>"
            ),
            status_code=503,
        )


@app.post("/predict", response_model=PredictionResponse)
def predict(
    req: PredictionRequest,
    bundle: Annotated[ModelBundle | None, Depends(get_bundle)],
) -> PredictionResponse:
    """Run inference. The request's `features` dict is reindexed to the
    model's training-time column order; missing columns default to 0."""
    if bundle is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    if bundle.feature_names:
        row = pd.DataFrame([req.features]).reindex(columns=bundle.feature_names, fill_value=0.0)
    else:
        row = pd.DataFrame([req.features])

    X = row.to_numpy(dtype=float)
    pred = int(bundle.model.predict(X)[0])
    proba_default = float(bundle.model.predict_proba(X)[0, 1])

    # Capture for drift analysis (batched flush to MinIO Parquet)
    _PREDICTION_BUFFER.append(
        capture_row(
            request_id=req.request_id or "",
            features={k: float(v) for k, v in req.features.items()},
            prediction=pred,
            probability_default=proba_default,
            model_version=str(bundle.version),
        )
    )
    _maybe_flush_buffer()

    return PredictionResponse(
        prediction=pred,
        probability_default=proba_default,
        model_version=str(bundle.version),
        request_id=req.request_id,
    )
